### ISSUE TITLE
color matching and layout touchups

### ISSUE THREAD

**Issue by girishramnani** [girishramnani/NuTech_16#5]
@tirth97 can you check the color of the whole website and also check for some problems if any.

**Comment by tirth97** [comment]
Ok will look at it.

**Comment by tirth97** [comment]
![screenshot 83](https://cloud.githubusercontent.com/assets/16166185/13047450/2c587716-d405-11e5-9943-5f3a6e602566.png)
![screenshot 84](https://cloud.githubusercontent.com/assets/16166185/13047451/2c599e66-d405-11e5-8489-331664527e98.png)
![screenshot 85](https://cloud.githubusercontent.com/assets/16166185/13047452/2c5d9ee4-d405-11e5-89e7-328e65fcb550.png)

Have a look at all the 3 pics especially at the Navigation bar in the bottom. All 3 are of different sizes.

**Comment by girishramnani** [comment]
Try to resolve this issue
